<a href="<?php echo $this->url(array('controller'=>'jeu')) ?>">Aller jouer !</a>









<!--<table>
    <caption>Bienvenue sur Dusk</caption>
    <tr>
        <td>
            <form method="post" action="" accept-charset="UTF-8" enctype="application/x-www-form-urlencoded">
                <table>
                    <caption>Vous avez déjà un compte</caption>
                    <tr>
                        <td><?php echo $this->form1->login ?></td>
                        <td><?php echo $this->form1->pass ?></td>
                    </tr>
                    <tr>
                        <td><?php echo $this->form1->connexion_auto ?></td>
                    </tr>
                    <tr>
                        <td><?php echo $this->form1->valider ?></td>
                    </tr>
                </table>
            </form>
        </td>
        <td>
            <form method="post" action="" accept-charset="UTF-8" enctype="application/x-www-form-urlencoded">
                <table>
                    <caption>Inscrivez-vous !</caption>
                    <tr>
                        <td><?php echo $this->form2->login ?></td>
                    </tr>
                    <tr>
                        <td><?php echo $this->form2->pass1 ?></td>
                    </tr>
                    <tr>
                        <td><?php echo $this->form2->pass2 ?></td>
                    </tr>
                    <tr>
                        <td><?php echo $this->form2->captcha
                        //$captcha=new Zend_Service_ReCaptcha('6Le2D8MSAAAAAHY3S-AM0a9yhJFitqkF56HZIrN-', '6Le2D8MSAAAAAOv2H2bFzKAyd8wgWTjSS26oTguL'); echo $captcha->getHtml()?></td>
                    </tr>
                    <tr>
                        <td><?php echo $this->form2->valider ?></td>
                    </tr>
                </table>
            </form>
        </td>
    </tr>
</table>-->