<table width="100%">
    <tr>
        <td style="vertical-align: top; width:20%">
            <a href="<?php echo $this->url(array('action'=>'recap')) ?>">
                <img style="float:right;"src="<?php echo $this->baseUrl()."/public/images/avatars/".$this->avatar.".jpg" ?>" alt="" />
            </a>
        </td>
        <td>
            <div style="float:left;width:80%;">
                <p>coin</p>
            </div>
        </td>
    </tr>
</table>