<table>
    <tr>
        <td id="case-portrait">
            <a href="#"><img src="<?php echo $this->baseUrl(),"/public/images/portraits/essai.jpg" ?>" alt="Mon portrait" title="Mon portrait"/></a>
        </td>
    </tr>
    <tr>
        <th><a href="#">Équipe</a></th>
    </tr>
    <tr>
        <td>
            <ul>
                <li><a href="#">Fiches</a></li>
                <li><a href="#">Blabla</a></li>
                <li><a href="#">Blablu</a></li>
            </ul>
        </td>
    </tr>
    <tr>
        <th><a href="#">Autre truc</a></th>
    </tr>
    <tr>
        <td>
            <ul>
                <li><a href="#">Pouinus</a></li>
                <li><a href="#">Gnagnagna</a></li>
            </ul>
        </td>
    </tr>
</table>